/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/rpe-submission`; params?: Router.UnknownInputParams; } | { pathname: `/wellness-checkin`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/pin-login` | `/pin-login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/setup` | `/setup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(coach)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(coach-auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/checkin` | `/checkin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownInputParams; } | { pathname: `${'/(coach)'}/add-members/[teamId]` | `/add-members/[teamId]`, params: Router.UnknownInputParams & { teamId: string | number; } } | { pathname: `${'/(coach)'}/team/[id]` | `/team/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/rpe-submission`; params?: Router.UnknownOutputParams; } | { pathname: `/wellness-checkin`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/pin-login` | `/pin-login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/setup` | `/setup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(coach)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(coach-auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/checkin` | `/checkin`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(coach)'}/add-members/[teamId]` | `/add-members/[teamId]`, params: Router.UnknownOutputParams & { teamId: string; } } | { pathname: `${'/(coach)'}/team/[id]` | `/team/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/rpe-submission${`?${string}` | `#${string}` | ''}` | `/wellness-checkin${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/pin-login${`?${string}` | `#${string}` | ''}` | `/pin-login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/setup${`?${string}` | `#${string}` | ''}` | `/setup${`?${string}` | `#${string}` | ''}` | `${'/(coach)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(coach-auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/checkin${`?${string}` | `#${string}` | ''}` | `/checkin${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/stats${`?${string}` | `#${string}` | ''}` | `/stats${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/rpe-submission`; params?: Router.UnknownInputParams; } | { pathname: `/wellness-checkin`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/pin-login` | `/pin-login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/setup` | `/setup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(coach)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(coach-auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/checkin` | `/checkin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownInputParams; } | `${'/(coach)'}/add-members/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/add-members/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(coach)'}/team/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/team/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(coach)'}/add-members/[teamId]` | `/add-members/[teamId]`, params: Router.UnknownInputParams & { teamId: string | number; } } | { pathname: `${'/(coach)'}/team/[id]` | `/team/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
